# Generated by Django 3.2.6 on 2021-12-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='criticism',
            name='critic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user'),
        ),
        migrations.DeleteModel(
            name='Critic',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='db.usertype'),
            preserve_default=False,
        ),
    ]
